export const SET_STORAGE_STATUS = 'SET_STORAGE_STATUS';
export const FETCH_WALLET_LIST = 'FETCH_WALLET_LIST';
export const SET_PROFILE_USER = 'SET_PROFILE_USER';
export const SET_LIST_HYPE = 'SET_LIST_HYPE';
export const SET_OFF_FIRST_TIME_RENDER = 'SET_OFF_FIRST_TIME_RENDER';
